# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_freestiler_wrappers", use_symbols = TRUE, package_name = "freestiler")

#' @usage NULL
#' @useDynLib freestiler, .registration = TRUE
NULL

#' Create vector tiles from spatial data
#'
#' @param geometries sfc list of sfg geometry objects
#' @param geom_types Character vector of geometry types
#' @param prop_names Character vector of property column names
#' @param prop_types Character vector of property types
#' @param prop_char_values List of character property columns
#' @param prop_num_values List of numeric property columns
#' @param prop_int_values List of integer property columns
#' @param prop_lgl_values List of logical property columns
#' @param output_path Path for output .pmtiles file
#' @param layer_name Name of the tile layer
#' @param tile_format "mvt" or "mlt"
#' @param min_zoom Minimum zoom level
#' @param max_zoom Maximum zoom level
#' @param do_simplify Whether to simplify geometries at lower zooms
#' @param generate_ids Whether to generate sequential feature IDs
#' @param quiet Whether to suppress progress messages
#' @return The output file path or an error message
#' @keywords internal
rust_freestile <- function(geometries, geom_types, prop_names, prop_types, prop_char_values, prop_num_values, prop_int_values, prop_lgl_values, output_path, layer_name, tile_format, min_zoom, max_zoom, do_simplify, generate_ids, quiet) .Call(wrap__rust_freestile, geometries, geom_types, prop_names, prop_types, prop_char_values, prop_num_values, prop_int_values, prop_lgl_values, output_path, layer_name, tile_format, min_zoom, max_zoom, do_simplify, generate_ids, quiet)


# nolint end
